/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DailyEntry = IDL.Record({
  'sensoryGuardingRating' : IDL.Float64,
  'speechPracticeCycles' : IDL.Nat,
  'physicalEnergyRating' : IDL.Float64,
  'eyeRelaxationRating' : IDL.Float64,
  'outsideFood' : IDL.Bool,
  'screenTimeMinutes' : IDL.Float64,
  'baselinePurityRating' : IDL.Float64,
  'fantasyRuminationRating' : IDL.Float64,
  'procrastinationRating' : IDL.Float64,
  'sleepRecharge' : IDL.Float64,
  'pranayamaMinutes' : IDL.Float64,
  'nadiShodhanSessions' : IDL.Float64,
  'deepWorkHours' : IDL.Float64,
  'microRestRating' : IDL.Float64,
  'mentalHealthRating' : IDL.Float64,
  'daySatisfactionRating' : IDL.Float64,
  'passivePhoneRating' : IDL.Float64,
  'uTurnEfficiencyRating' : IDL.Float64,
  'shutdownRitual' : IDL.Bool,
  'pmoOccurrence' : IDL.Bool,
  'guruPranamMinutes' : IDL.Float64,
});
export const WeeklyHobbies = IDL.Record({
  'storyWriting' : IDL.Bool,
  'guitar' : IDL.Bool,
  'poetry' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllDailyEntryDates' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyEntriesByDates' : IDL.Func(
      [IDL.Vec(IDL.Text)],
      [IDL.Vec(IDL.Tuple(IDL.Text, DailyEntry))],
      ['query'],
    ),
  'getDailyEntry' : IDL.Func([IDL.Text], [IDL.Opt(DailyEntry)], ['query']),
  'getEntriesForWeek' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Vec(IDL.Tuple(IDL.Text, DailyEntry))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWeeklyHobbies' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(WeeklyHobbies)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveDailyEntry' : IDL.Func([IDL.Text, DailyEntry], [], []),
  'saveWeeklyHobbies' : IDL.Func([IDL.Text, WeeklyHobbies], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DailyEntry = IDL.Record({
    'sensoryGuardingRating' : IDL.Float64,
    'speechPracticeCycles' : IDL.Nat,
    'physicalEnergyRating' : IDL.Float64,
    'eyeRelaxationRating' : IDL.Float64,
    'outsideFood' : IDL.Bool,
    'screenTimeMinutes' : IDL.Float64,
    'baselinePurityRating' : IDL.Float64,
    'fantasyRuminationRating' : IDL.Float64,
    'procrastinationRating' : IDL.Float64,
    'sleepRecharge' : IDL.Float64,
    'pranayamaMinutes' : IDL.Float64,
    'nadiShodhanSessions' : IDL.Float64,
    'deepWorkHours' : IDL.Float64,
    'microRestRating' : IDL.Float64,
    'mentalHealthRating' : IDL.Float64,
    'daySatisfactionRating' : IDL.Float64,
    'passivePhoneRating' : IDL.Float64,
    'uTurnEfficiencyRating' : IDL.Float64,
    'shutdownRitual' : IDL.Bool,
    'pmoOccurrence' : IDL.Bool,
    'guruPranamMinutes' : IDL.Float64,
  });
  const WeeklyHobbies = IDL.Record({
    'storyWriting' : IDL.Bool,
    'guitar' : IDL.Bool,
    'poetry' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllDailyEntryDates' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyEntriesByDates' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [IDL.Vec(IDL.Tuple(IDL.Text, DailyEntry))],
        ['query'],
      ),
    'getDailyEntry' : IDL.Func([IDL.Text], [IDL.Opt(DailyEntry)], ['query']),
    'getEntriesForWeek' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Vec(IDL.Tuple(IDL.Text, DailyEntry))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWeeklyHobbies' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(WeeklyHobbies)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveDailyEntry' : IDL.Func([IDL.Text, DailyEntry], [], []),
    'saveWeeklyHobbies' : IDL.Func([IDL.Text, WeeklyHobbies], [], []),
  });
};

export const init = ({ IDL }) => { return []; };