/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailyEntry {
  'sensoryGuardingRating' : number,
  'speechPracticeCycles' : bigint,
  'physicalEnergyRating' : number,
  'eyeRelaxationRating' : number,
  'outsideFood' : boolean,
  'screenTimeMinutes' : number,
  'baselinePurityRating' : number,
  'fantasyRuminationRating' : number,
  'procrastinationRating' : number,
  'sleepRecharge' : number,
  'pranayamaMinutes' : number,
  'nadiShodhanSessions' : number,
  'deepWorkHours' : number,
  'microRestRating' : number,
  'mentalHealthRating' : number,
  'daySatisfactionRating' : number,
  'passivePhoneRating' : number,
  'uTurnEfficiencyRating' : number,
  'shutdownRitual' : boolean,
  'pmoOccurrence' : boolean,
  'guruPranamMinutes' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WeeklyHobbies {
  'storyWriting' : boolean,
  'guitar' : boolean,
  'poetry' : boolean,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllDailyEntryDates' : ActorMethod<[], Array<string>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailyEntriesByDates' : ActorMethod<
    [Array<string>],
    Array<[string, DailyEntry]>
  >,
  'getDailyEntry' : ActorMethod<[string], [] | [DailyEntry]>,
  'getEntriesForWeek' : ActorMethod<
    [string, Array<string>],
    Array<[string, DailyEntry]>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWeeklyHobbies' : ActorMethod<[string], [] | [WeeklyHobbies]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveDailyEntry' : ActorMethod<[string, DailyEntry], undefined>,
  'saveWeeklyHobbies' : ActorMethod<[string, WeeklyHobbies], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];